import React, { useEffect, useRef, useState } from 'react';
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom';
import { Activity, ArrowRight, Building2, Check, ChevronDown, CircleAlert, Copy, Download, FileImage, Layers3, LockKeyhole, ScanLine, ShieldCheck, UploadCloud, X } from 'lucide-react';
import { toast, Toaster } from 'sonner';
import { analyzeImage } from './services/analysisService';
import './App.css';

const MAX_SIZE = 25 * 1024 * 1024;
const imageModes = { Original: 'https://images.unsplash.com/photo-1579567761406-4684ee0c75b6', ELA: 'https://images.unsplash.com/photo-1640941295021-a2f78b997312', Heatmap: 'https://images.unsplash.com/photo-1778716007446-1a808781664a' };

function Navbar() {
  const [open, setOpen] = useState(false);
  return <header className="topbar" data-testid="navbar">
    <div className="nav-inner">
      <Link to="/" className="brand" data-testid="brand-link"><span className="brand-mark"><ShieldCheck size={19} /></span><span><span className="brand-name">MedTrace</span><span className="brand-tag">AI</span></span></Link>
      <nav className="nav-links" data-testid="main-navigation"><NavLink to="/" end>Home</NavLink><NavLink to="/about">About Us</NavLink></nav>
      <div className="org-menu"><button className="org-trigger" onClick={() => setOpen(!open)} data-testid="organization-menu-button"><Building2 size={14} color="var(--cyan)" /><span>MedTrace</span><ChevronDown size={13} /></button>
        {open && <div className="org-popover" data-testid="organization-menu"><p>Organization workspace</p><strong data-testid="organization-name">MedTrace</strong><button data-testid="account-settings-button" onClick={() => toast.info('Account settings are available to your organization administrator.')}>Account settings</button><button data-testid="logout-button" onClick={() => { setOpen(false); toast.success('You have been securely signed out.'); }}>Log out</button></div>}
      </div>
    </div>
  </header>;
}

function Footer() { return <footer className="footer"><div className="content-width footer-inner"><span data-testid="footer-description">MedTrace AI · AI-powered medical image authenticity and integrity verification.</span><span><Link to="/">Home</Link><Link to="/about">About</Link><a href="#privacy" data-testid="privacy-link">Privacy</a><a href="#terms" data-testid="terms-link">Terms</a></span></div></footer>; }

function Pipeline() { return <div className="pipeline" data-testid="analysis-pipeline"><div className="pipeline-title">FORENSIC ANALYSIS PIPELINE / READY</div><div className="pipeline-row"><div className="pipeline-step"><div className="pipeline-icon"><FileImage size={19} /></div><span>Original scan</span></div><ArrowRight className="pipeline-arrow" size={18} /><div className="pipeline-step"><div className="pipeline-icon"><ScanLine size={19} /></div><span>ELA representation</span></div><ArrowRight className="pipeline-arrow" size={18} /><div className="pipeline-step"><div className="pipeline-icon"><ShieldCheck size={19} /></div><span>Integrity signal</span></div></div></div>; }

function UploadZone({ onFile, busy }) {
  const input = useRef(); const [dragging, setDragging] = useState(false);
  const accept = (file) => { if (!file) return; if (file.size > MAX_SIZE) return toast.error('File exceeds the maximum supported size of 25 MB.'); const valid = file.type.startsWith('image/') || file.name.toLowerCase().endsWith('.dcm'); if (!valid) return toast.error('Unsupported format. Please upload DICOM, PNG, JPG or JPEG.'); onFile(file); };
  return <div className={`upload-zone ${dragging ? 'dragging' : ''}`} onClick={() => !busy && input.current?.click()} onDragOver={(e) => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(e) => { e.preventDefault(); setDragging(false); accept(e.dataTransfer.files[0]); }} data-testid="upload-dropzone">
    <input ref={input} type="file" accept="image/*,.dcm" hidden onChange={(e) => accept(e.target.files[0])} data-testid="medical-image-file-input" />
    <div><div className="upload-icon"><UploadCloud size={24} /></div><h3>{busy ? 'Preparing verification…' : 'Drop your medical image here'}</h3><p>or browse files from your workstation</p><span className="browse">DICOM · PNG · JPG · JPEG</span><p style={{ marginTop: 17 }}>Maximum file size: 25 MB · Images are not retained</p></div>
  </div>;
}

function Progress({ file, step, stage }) { const stages = ['Uploading', 'Preprocessing', 'ELA Analysis', 'Dual-ViT Analysis', 'Generating Explainability', 'Verifying Integrity']; return <div className="progress-wrap" data-testid="analysis-progress"><div className="progress-head"><h2>Analyzing image signal</h2><span data-testid="current-analysis-stage">{stage}</span></div><p style={{ color: 'var(--muted)', fontSize: 12 }} data-testid="processing-file-name">{file.name}</p><div className="progress-track"><div className="progress-fill" style={{ width: `${((step + 1) / stages.length) * 100}%` }} /></div><div className="stage-list">{stages.map((name, index) => <div className={`stage ${index < step ? 'done' : ''} ${index === step ? 'current' : ''}`} key={name} data-testid={`analysis-stage-${index}`}><div className="stage-dot" />{name}</div>)}</div></div>; }

function FileBar({ file, onAnalyze, onRemove }) { return <div className="file-bar" data-testid="selected-file-bar"><div className="file-meta"><FileImage color="var(--cyan)" size={20} /><div><strong data-testid="selected-file-name">{file.name}</strong><small data-testid="selected-file-details">{(file.size / 1024 / 1024).toFixed(2)} MB · {file.type || 'DICOM image'}</small></div></div><div style={{ display: 'flex', gap: 7 }}><button className="button ghost" onClick={onRemove} data-testid="remove-file-button"><X size={14} /> Remove</button><button className="button primary" onClick={onAnalyze} data-testid="analyze-image-button">Analyze image <ArrowRight size={14} /></button></div></div>; }

function Probabilities({ result }) { const rows = [['Authentic', result.probabilities.authentic, ''], ['Tampered', result.probabilities.tampered, 'warn'], ['AI-generated', result.probabilities.ai_generated, 'alert']]; return <div className="panel" data-testid="probability-panel"><h3>Confidence distribution</h3>{rows.map(([name, value, tone]) => <div className="prob-row" key={name}><div className="prob-label"><span>{name}</span><span data-testid={`probability-${name.toLowerCase().replace('-', '')}`}>{(value * 100).toFixed(1)}%</span></div><div className={`bar ${tone}`}><i style={{ width: `${value * 100}%` }} /></div></div>)}<div className="explain"><strong style={{ color: 'var(--white)' }}>AI analysis</strong><br />{result.summary}</div><div className="disclaimer" data-testid="diagnostic-disclaimer">Model attention indicates digital authenticity signals only. This is not clinical diagnostic evidence.</div></div>; }

function Results({ result, file, reset }) { const [mode, setMode] = useState('Original'); const copy = () => { navigator.clipboard?.writeText(result.verificationId); toast.success('Verification ID copied.'); }; const download = () => { const blob = new Blob([`MedTrace AI forensic report\nPrediction: ${result.prediction}\nConfidence: ${(result.confidence * 100).toFixed(1)}%\nVerification ID: ${result.verificationId}`], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'medtrace-verification-report.txt'; a.click(); URL.revokeObjectURL(url); toast.success('Report downloaded.'); };
  return <section className="results content-width" data-testid="analysis-results"><div className="result-head"><div className="result-status"><div className="status-mark"><ShieldCheck size={25} /></div><div><div className="eyebrow">Authenticity result</div><h2 data-testid="prediction-result">{result.prediction}</h2><p data-testid="confidence-result">Confidence {(result.confidence * 100).toFixed(1)}% · {file.name}</p></div></div><div className="result-actions"><button className="button ghost" onClick={copy} data-testid="copy-verification-id-button"><Copy size={14} /> Copy ID</button><button className="button primary" onClick={download} data-testid="download-report-button"><Download size={14} /> Download report</button><button className="button ghost" onClick={reset} data-testid="analyze-another-button">Analyze another</button></div></div><div className="result-grid"><div className="panel"><div className="section-label"><h3>Image comparison</h3><span className="eyebrow">Dual-input inspector</span></div><div className="tabs">{Object.keys(imageModes).map((item) => <button className={`tab ${mode === item ? 'active' : ''}`} onClick={() => setMode(item)} key={item} data-testid={`comparison-tab-${item.toLowerCase()}`}>{item}</button>)}</div><div className="viewer" data-testid="comparison-viewer"><img src={file.preview || imageModes[mode]} alt={`${mode} medical image representation`} /><div className="viewer-label">VIEW / {mode.toUpperCase()}</div>{mode === 'Heatmap' && <div className="heat-overlay" data-testid="mock-heatmap-overlay" />}</div><p style={{ color: 'var(--muted)', fontSize: 11, margin: '12px 0 0' }}>Simulated forensic visualization for this preview. Suspicion overlays represent model attention, not anatomy.</p></div><Probabilities result={result} /></div><p style={{ color: 'var(--muted)', fontSize: 11, marginTop: 18 }} data-testid="verification-id">Verification ID: {result.verificationId} · Completed {new Date(result.timestamp).toLocaleTimeString()}</p></section>; }

function Home() { const [file, setFile] = useState(null); const [busy, setBusy] = useState(false); const [step, setStep] = useState(0); const [stage, setStage] = useState(''); const [result, setResult] = useState(null); useEffect(() => () => file?.preview && URL.revokeObjectURL(file.preview), [file]); const choose = (item) => { if (item) setFile(Object.assign(item, { preview: item.type?.startsWith('image/') ? URL.createObjectURL(item) : null })); setResult(null); }; const analyze = async () => { setBusy(true); setResult(null); const data = await analyzeImage(file, (index, current) => { setStep(index); setStage(current); }); setBusy(false); setResult(data); toast.success(`Verification complete: ${data.prediction}`); }; return <main><div className="content-width hero"><div><div className="eyebrow">MedTrace AI / Verification console</div><h1>Verify what your <em>medical images</em> reveal.</h1><p className="hero-copy">MedTrace AI analyzes medical images for manipulation and synthetic generation, combining vision-based forensic analysis with clear, operational evidence.</p></div><Pipeline /></div>{!busy && !result && <section className="content-width" style={{ paddingBottom: 90 }}><div className="section-label"><div><h2>Start a verification</h2><p>Upload one image to begin a dual-input authenticity review.</p></div><span className="eyebrow">Workspace / ready</span></div><UploadZone onFile={choose} busy={busy} />{file && <FileBar file={file} onAnalyze={analyze} onRemove={() => setFile(null)} />}</section>}{busy && <Progress file={file} step={step} stage={stage} />}{result && <Results result={result} file={file} reset={() => { setResult(null); setFile(null); }} />}</main>; }

function About() { return <main className="about content-width" data-testid="about-page"><div className="about-intro"><div className="eyebrow">About MedTrace AI</div><h1>Authenticity for the greater good.</h1><p>MedTrace AI helps organizations understand whether a medical image is authentic, or synthetically generated. It is an authenticity platform, not a diagnosis tool.</p></div><div className="about-grid"><article className="about-block"><h2>What we examine</h2><p>Our dual-input Vision Transformer compares the original scan with an Error Level Analysis representation to surface inconsistencies that ordinary inspection can miss.</p></article><article className="about-block"><h2>Why it matters</h2><ul><li>Protect research and medical record integrity</li><li>Support insurance and forensic review</li><li>Identify manipulated or AI-generated content</li></ul></article><article className="about-block" style={{ gridColumn: '1 / -1' }}><h2>How the signal is built</h2><div className="steps">{[['01','Upload'],['02','Preprocess'],['03','AI detection'],['04','Explainability'],['05','Integrity review']].map(([n, label]) => <div className="step-card" key={n} data-testid={`about-step-${n}`}><span>{n}</span><b>{label}</b></div>)}</div></article><article className="about-block"><h2>Technology</h2><p><Layers3 size={15} color="var(--cyan)" /> Dual Vision Transformer<br /><ScanLine size={15} color="var(--cyan)" /> Error Level Analysis<br /><Activity size={15} color="var(--cyan)" /> Explainable attention mapping</p></article><article className="about-block"><h2>Built for teams</h2><p>Hospitals, diagnostic centers, medical research organizations, insurance organizations, and healthcare forensic teams.</p></article></div></main>; }

export default function App() { return <BrowserRouter><div className="app-shell"><Toaster theme="dark" position="top-right" /><Navbar /><Routes><Route path="/" element={<Home />} /><Route path="/about" element={<About />} /></Routes><Footer /></div></BrowserRouter>; }